### ISSUE TITLE
Can Persistence.Reminders be used to store large set of reminders over a long period?

### ISSUE THREAD

**Issue by object** [Horusiath/Akka.Persistence.Reminders#9]
We are currently using both Akka.Persistence.Reminders and a table in a database to store different types of reminders. The former is used to set up a small number of short term reminders, the latter is to store long-term reminders that can be triggered after several days or even months or years.

We were thinking about unifying reminders but it looks to me that since there reminders are using event journal to store reminders and build its in-memory state from it they are not really suited for storing large sets of reminders over a long time and such scenario requires different implementation. Am I correct?

**Comment by Horusiath** [comment]
While it depends what you mean by large set, yes - reminder is using eventsourcing to create an in-memory "table" of known reminders to be called. This could be changed, but it requires changing the implementation.

**Comment by object** [comment]
Thanks. I am thinking about a scenario where domain consists of large number of entities (let's say bank accounts) and reminders can be set on some entities over a long period. So while there are just few reminders to be triggered within a short time (let's say few hundreds every hour or day), there may be millions of reminders in the system scheduled to be triggered in a few months or years. In such case it will become inefficient to represent state as a collection of all reminders.

Perhaps an alternative implementation might use instead of a single persistent actor a group of actors working on limited intervals. With a single dispatcher that activate those that match the current time. But that will be quite a big change.

**Comment by Horusiath** [comment]
Sorry for responding so late, but I only recently noticed that I haven't respond. While you're probably already figured out a different solution, I'll leave it here for the future.

So, the general issue is that reminder is an actor, which stores the scheduled messages in it's own state - in akka actor's state is expected to **be fine grained** and fit into memory. The issue is that the total schedule may be bigger than memory. Given the possibilities of persistent state offered on Akka.Persistence alone (and we want to maintain these) we cannot have only "a piece of state" in the memory.

The way to work out with that - that I could imagine - would be to have multiple reminder actors instead of one. One actor per each slice of time eg. each quarter or so, depending on the needs. 

- Actors that are supposed to be run in a distant future are only spawned when new reminder event needs to be scheduled on them. Otherwise, they stay dead - only their state is persisted. 
- The only active reminder is the one which schedule overlaps with the present date.
- At the end of active reminder schedule window it triggers an event that handles over the active responsibilities to the reminder actor responsible for the next time period. 

Necessary tools are already in place: reminders can have different persistence ids using `Reminder.Props(reminderSettings.WithPersistenceId(timeWindow))`, while a `timeWindow` name can be a function of a given date (like `yyyy/MM`). 

Maybe it would be feasible to change that pattern into a separate parent actor wrapping the reminders.

**Comment by object** [comment]
@Horusiath thank you for the clarification. It makes sense and I think using multiple Ids is the way to go. But one thing that is not clear in such case: how different persistent Ids should be configured? In your documentation it looks like this:

akka.persistence.reminder {

	# Persistent identifier for event stream produced by correlated reminder.
	persistence-id = "reminder"
        ...
}

I.e. it's only single ID that is specified in the configuration. What should I write in the HOCON file to make it multiple? Or do you mean that when using Reminder.Props(reminderSettings.WithPersistenceId(timeWindow)) I don't need to specify persistence-id in HOCON?

**Comment by Horusiath** [comment]
`Reminder` constructor and `Props` factory method can take a configuration object as a parameter. PersistenceId is one of the properties of that configuration object. You can use create different configuration every time you need to create a reminder. If that object was not provided, [it will be created from HOCON configuration](https://github.com/Horusiath/Akka.Persistence.Reminders/blob/master/Akka.Persistence.Reminders/Reminder.cs#L50) section automatically.

**Comment by object** [comment]
Oh that makes it perfectly clear thanks!
